### ISSUE TITLE
TF2.0: no supported kernel for GPU devices is available

### ISSUE THREAD

**Issue by MoYinYu** [noahchalifour/rnnt-speech-recognition#20]
Thank you for your code, but I encountered an error running "run_common_voice. py".
That is：
Traceback (most recent call last):
  File "run_common_voice.py", line 547, in <module>
    app.run(main)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_common_voice.py", line 506, in main
    gpus=gpus)
  File "run_common_voice.py", line 257, in run_training
    train()
  File "run_common_voice.py", line 230, in train
    loss, metrics_results = train_step(inputs)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 520, in _call
    return self._stateless_fn(*args, **kwds)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/data0/tclxa/tfenv/anaconda3/envs/tf20/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation transducer/prediction_network/embedding/embedding_lookup/ReadVariableOp: Could not satisfy explicit device specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
GatherV2: GPU CPU XLA_CPU XLA_GPU 
Cast: GPU CPU XLA_CPU XLA_GPU 
Const: GPU CPU XLA_CPU XLA_GPU 
_Arg: GPU CPU XLA_CPU XLA_GPU 
ResourceSparseApplyKerasMomentum: CPU 
ReadVariableOp: GPU CPU XLA_CPU XLA_GPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  transducer_prediction_network_embedding_embedding_lookup_readvariableop_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  sgd_sgd_update_20_update_0_resourcesparseapplykerasmomentum_accum (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  transducer/prediction_network/embedding/embedding_lookup/ReadVariableOp (ReadVariableOp) /job:localhost/replica:0/task:0/device:GPU:0
  transducer/prediction_network/embedding/embedding_lookup/axis (Const) /job:localhost/replica:0/task:0/device:GPU:0
  transducer/prediction_network/embedding/embedding_lookup (GatherV2) /job:localhost/replica:0/task:0/device:GPU:0
  Shape_22 (Const) /job:localhost/replica:0/task:0/device:GPU:0
  Cast_4 (Cast) /job:localhost/replica:0/task:0/device:GPU:0
  SGD/SGD/update_20/update_0/ResourceSparseApplyKerasMomentum (ResourceSparseApplyKerasMomentum) /job:localhost/replica:0/task:0/device:GPU:0

Op: ReadVariableOp
Node attrs: dtype=DT_FLOAT
Registered kernels:
  device='XLA_CPU_JIT'; dtype in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_BFLOAT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]
  device='XLA_GPU_JIT'; dtype in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT8, ..., DT_BFLOAT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64cudnn=7.6]
  device='GPU'
  device='CPU'
  device='XLA_CPU'
  device='XLA_GPU'

	 [[{{node transducer/prediction_network/embedding/embedding_lookup/ReadVariableOp}}]] [Op:__inference_train_step_94552]

System infomation:
Ubuntu 16.04,   tensorflow-gpu2.0,  cudnn=7.4,  cudatoolkit=10.0。

**Comment by MoYinYu** [comment]
This may be due to the use of multiple GPUs. I solved this problem by setting strategy = None. And some code in run_common_voice.py/run_evaluate(...) are change to be：

        if strategy is not None:
            losses, metrics_results = strategy.experimental_run_v2(step_fn, args=(dist_inputs,))
            mean_loss = strategy.reduce(
                tf.distribute.ReduceOp.SUM, losses, axis=0)
            mean_metrics = {name: strategy.reduce(
                tf.distribute.ReduceOp.SUM, result, axis=0) for name, result in metrics_results.items()}
        else:
            losses, metrics_results = step_fn(dist_inputs)
            mean_loss = tf.reduce_sum(losses, axis=0)
            mean_metrics = {name: tf.reduce_sum(result, axis=0) for name, result in metrics_results.items()}
