### ISSUE TITLE
TF2.1 : AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'

### ISSUE THREAD

**Issue by MoYinYu** [noahchalifour/rnnt-speech-recognition#21]
Thank you for your code, but I encountered an error running "run_common_voice. py".
That is：

(tf21) tclxa@GPU245:/data0/tclxa/workspace/tangyanhuan/rnnt-speech-recognition-master$ python run_common_voice.py --mode train --data_dir /data0/tclxa/workspace/tangyanhuan/data/zhCN/zhcn_data 
2020-04-22 18:01:17.360854: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:
2020-04-22 18:01:17.361024: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: .:
2020-04-22 18:01:17.361049: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "run_common_voice.py", line 15, in <module>
    from utils.loss import get_loss_fn
  File "/data0/tclxa/workspace/tangyanhuan/rnnt-speech-recognition-master/utils/loss.py", line 6, in <module>
    from warprnnt_tensorflow import rnnt_loss
  File "/data0/tclxa/tfenv/anaconda3/envs/tf21/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg/warprnnt_tensorflow/__init__.py", line 44, in <module>
    @ops.RegisterShape("WarpRNNT")
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'

System infomation:
Ubuntu 16.04, tensorflow-gpu2.1, cudnn=7.6, cudatoolkit=10.1。

**Comment by NAM-hj** [comment]
I had that issue too. 

[Situation]
I think you get the same error when you import warp-transducer.
try to run this code in python
`from warprnnt_tensorflow import rnnt_loss`

[My situation]
I'm not sure about your error, but I downloaded warp-transducer from the original link (https://github.com/HawkAaron/warp-transducer) at first.

[My solution]
So I re-install
cuda=10.1
tensorflow-gpu=2.1.0
warp-transducer from here (It is the same link which is in https://github.com/noahchalifour/rnnt-speech-recognition)
> https://github.com/noahchalifour/warp-transducer/tree/ecbd47e038de6282355897e6a52e56c01999435a


After that, I can move on.

I hope it helps you.

```
[My system]
GPU : GTX 1080ti * 4
OS : ubuntu 18.04
NVIDIA Driver : 440.82
CUDA : 10.1
CUDNN : 7.6.5
python : 3.6.9
tensorflow & tensorflow-gpu : 2.1.0
```

**Comment by MoYinYu** [comment]
@nambee Thanks. I run warprnnt_tensorflow in tf2.0. It works well. I think the error may be due to my installation of cudatoolkit10.1 with conda.
