### ISSUE TITLE
ValueError: Python inputs incompatible with input_signature

### ISSUE THREAD

**Issue by dyc3** [noahchalifour/rnnt-speech-recognition#27]
I pulled the latest code, and ran

```
python run_rnnt.py --mode train --data_dir data_p --batch_size 4 --steps_per_checkpoint 100 --eval_size 100
```

Output
```
Traceback (most recent call last):
  File "run_rnnt.py", line 587, in <module>
    app.run(main)
  File "/home/carson/Documents/code/other/rnnt-speech-recognition/.env/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/carson/Documents/code/other/rnnt-speech-recognition/.env/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_rnnt.py", line 546, in main
    eval_metrics=[accuracy_fn, wer_fn])
  File "run_rnnt.py", line 347, in run_training
    checkpoint_model()
  File "run_rnnt.py", line 312, in checkpoint_model
    metrics=eval_metrics)
  File "run_rnnt.py", line 433, in run_evaluate
    loss, metrics_results = eval_step(inputs)
  File "/home/carson/Documents/code/other/rnnt-speech-recognition/.env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/carson/Documents/code/other/rnnt-speech-recognition/.env/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 648, in _call
    *args, **kwds)
  File "/home/carson/Documents/code/other/rnnt-speech-recognition/.env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2238, in canonicalize_function_inputs
    self._flat_input_signature)
  File "/home/carson/Documents/code/other/rnnt-speech-recognition/.env/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2305, in _convert_inputs_to_signature
    format_error_message(inputs, input_signature))
ValueError: Python inputs incompatible with input_signature:
  inputs: (
    (<tf.Tensor: shape=(4, 188, 80), dtype=float32, numpy=
array([[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        ...,
        [7.6508689e-01, 7.1499169e-01, 7.2347635e-01, ...,
         1.0061518e-01, 1.3225035e-01, 1.0957059e-01],
        [2.4028959e+00, 3.5814118e+00, 4.4974680e+00, ...,
         6.7717570e-01, 1.8958096e-01, 7.8275286e-02],
        [2.2969201e+00, 2.4087617e+00, 2.3480484e+00, ...,
         9.5862454e-01, 7.0159447e-01, 7.8365260e-01]],

       [[3.0718868e+00, 3.9090357e+00, 4.4902396e+00, ...,
         9.4585621e-01, 7.5401241e-01, 4.0395582e-01],
        [2.6149049e+00, 3.9459662e+00, 4.8865523e+00, ...,
         7.6179683e-01, 2.7078435e-01, 1.9691952e-01],
        [4.1796079e+00, 6.6662502e+00, 8.6251745e+00, ...,
         4.6787399e-01, 4.2361385e-01, 1.5892750e-01],
        ...,
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00]],

       [[3.1744879e-02, 3.7090626e-02, 4.0673282e-02, ...,
         1.1356002e-02, 7.9708314e-03, 5.3407014e-03],
        [2.2388861e-02, 1.5787246e-02, 1.0766077e-02, ...,
         7.9495674e-03, 6.4723925e-03, 3.4302704e-03],
        [5.7072259e-02, 8.2680024e-02, 9.6591927e-02, ...,
         8.6351167e-03, 9.3043121e-03, 4.3008928e-03],
        ...,
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00]],

       [[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [2.4114311e-02, 2.6643764e-02, 2.9123044e-02, ...,
         1.7673383e-02, 2.4660386e-02, 1.5520564e-02],
        [1.0082184e-01, 1.5430452e-01, 1.7339359e-01, ...,
         2.6907435e-02, 5.7685025e-02, 4.1620839e-02],
        ...,
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         0.0000000e+00, 0.0000000e+00, 0.0000000e+00]]], dtype=float32)>, <tf.Tensor: shape=(4, 15), dtype=int32, numpy=
array([[   1,  833,  676,    9, 1565, 1059, 3933,    3,  840, 2986, 3864,
        1022,  316,   87, 3878],
       [   1,  791,  244, 1754, 3864,   25,   70,   11,   70, 1399, 3878,
           0,    0,    0,    0],
       [   1,  884, 1778, 3864,  416, 3518, 3864,  523,    3,  758,  361,
          64, 3878,    0,    0],
       [   1,  198,   88,  130, 2233,    6, 1559, 3895,    0,    0,    0,
           0,    0,    0,    0]], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([188, 120, 132,  84], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([15, 11, 13,  8], dtype=int32)>, <tf.Tensor: shape=(4, 14), dtype=int32, numpy=
array([[ 833,  676,    9, 1565, 1059, 3933,    3,  840, 2986, 3864, 1022,
         316,   87, 3878],
       [ 791,  244, 1754, 3864,   25,   70,   11,   70, 1399, 3878,    0,
           0,    0,    0],
       [ 884, 1778, 3864,  416, 3518, 3864,  523,    3,  758,  361,   64,
        3878,    0,    0],
       [ 198,   88,  130, 2233,    6, 1559, 3895,    0,    0,    0,    0,
           0,    0,    0]], dtype=int32)>))
  input_signature: (
    [TensorSpec(shape=(None, None, 240), dtype=tf.float32, name=None), TensorSpec(shape=(None, None), dtype=tf.int32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None), TensorSpec(shape=(None, None), dtype=tf.int32, name=None)])
```

**Comment by noahchalifour** [comment]
@dyc3 The preprocessing scripts changed so you'll have to rerun that
